### ISSUE TITLE
Where is license?

### ISSUE THREAD

**Issue by Bittyby** [WPMGPRoSToTeMa/VoiceTranscoder#1]
kak eto ispolsovat 9 x3, license xde?
vseo, na server ne postavly, a to malo li babki poprosat ewo i ckajyt 4to kamynist!!1

**Comment by WPMGPRoSToTeMa** [comment]
Almost forgot about that, thanks.

**Comment by WPMGPRoSToTeMa** [comment]
I'll keep it open until #2 will be merged.
